In [85]:
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier

In [86]:
df = pd.read_csv("diabetes.csv")

In [87]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [88]:
target_columns = ["BloodPressure", "Insulin", "SkinThickness"]
X = df.drop(columns=target_columns)
y= df[target_columns]

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [90]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [91]:
svc=SVC(kernel='rbf') 
svc.fit(X_train, y_train)

ValueError: y should be a 1d array, got an array of shape (614, 3) instead.

In [ ]:
y_pred=svc.predict(X_test)
print('Model accuracy(SVM) : {0:0.3f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy(SVM) : 0.013


c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          62       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         1
          71       0.00      0.00      0.00         1
          73       0.00      0.00      0.00         1
          74       0.00      0.00      0.00         3
          75       0.00      0.00      0.00         1
          77       0.00      0.00      0.00         1
          78       0.00      0.00      0.00         1
          80       0.00      0.00      0.00         2
          81       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         2
          84       0.00      0.00      0.00         3
          85       0.00      0.00      0.00         2
          86       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         2
          89       0.00      0.00      0.00         1
          90       0.00    

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData\Local\Programs\P

In [ ]:
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [ ]:
y_pred = classifier.predict(X_test)
print(y_pred, y_test)

[100 111  99 130 125 120  99 119 126 132 125 105 124 120  90 109 111  99
 119 129 114 105  88  99 106 112  99 125 112 120 180 145 124 119 120 100
 144 128 194 141  99 137 120 164 125 173 176 111 120 165  99 136 187 130
 124  99 132  99 100 125 112 111 142 197 117  79  99 147 130 155 154 111
 114 107  99 105 137 100  95 117 125 109  99 105 100 129 151 128 111  99
  99 117  99 145 129  81 114 100 173 106 105 107 156 123 130 105 109 128
 128 100  99 130  99 112 100  87   0  99  99  99  99 100 112 118  99 144
 109 168 138 126 130 187  82 124 173  99 125 133 145  99  99  99 125 165
 107 100 118  99 105 125 100 120 124 100] 668     98
324    112
624    108
690    107
473    136
      ... 
355    165
534     77
344     95
296    146
462     74
Name: Glucose, Length: 154, dtype: int64


In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy (Logistics):", accuracy_score(y_test, y_pred))

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\multiclass.py:79: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  ys_types = set(type_of_target(x) for x in ys)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Accuracy (Logistics): 0.006493506493506494


c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")


In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(y_pred)
print(y_test)
print("KNN Accuracy:", accuracy_score(y_test, y_pred))

[144  86  92  44  99  92  91  87 105 110  84  61 128  65  71  93  83  91
 100  93  85  89  57  88  72   0  88  99 122  81 118 125 158 132  67  97
   0 115  94 119  99  57  61 108  87 105 128  80 120  81  99  90 100 113
  97  93 110  73  97  95  97  86 136 100 102  71  91 115  71 155 123  88
 110 112  73  61 114 103 104 106 107 107  85 112  84 128   0  93  88  98
  88 122  73  91  84  79  76  84 155  75  61  79 130  91 108 112 103 105
 128   0 100  82  84 112 107  87 109  76  99  90 111  71 103  84 111  88
  84 112 100  89 107 100  95  84 105  78 102 127  90  95   0 111 106 114
  92  65 100   0  77 133  84  91 128  65]
668     98
324    112
624    108
690    107
473    136
      ... 
355    165
534     77
344     95
296    146
462     74
Name: Glucose, Length: 154, dtype: int64
KNN Accuracy: 0.006493506493506494


c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")


In [ ]:
accuracy_scores = []
k_range = range(1, 21)

for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)
    accuracy_scores.append(accuracy_score(y_test, y_pred))

best_k = k_range[np.argmax(accuracy_scores)]
best_accuracy = max(accuracy_scores)

print("Best K value:", best_k)
print("Best Accuracy:", best_accuracy)

c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:99: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_pred = type_of_target(y_pred, input_name="y_pred")
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData

Best K value: 2
Best Accuracy: 0.025974025974025976


c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData

In [ ]:
print('Model accuracy(SVM) : {0:0.3f}'. format(accuracy_score(y_test, y_pred)))
print("Accuracy (Logistics):", accuracy_score(y_test, y_pred))
print("Best Accuracy(KNN):", best_accuracy)

Model accuracy(SVM) : 0.006
Accuracy (Logistics): 0.006493506493506494
Best Accuracy(KNN): 0.025974025974025976


c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
c:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:98: UserWarning: The number of unique classes is greater than 50% of the number of samples. `y` could represent a regression problem, not a classification problem.
  type_true = type_of_target(y_true, input_name="y_true")
